# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  json_field:         # id of input
    description: 'JSON field to update'
    required: true
  json_value:         # id of input
    description: 'New value for the JSON field'
    required: true
    default: 'Foo'
outputs:
  json_old_value:     # id of output
    description: 'The former value of the JSON field'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.json_field }}
    - ${{ inputs.json_value }}